language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

install:
  - sudo apt-get update
  - pip install pytest pysam
  - pip install pandas
script:
  # run the workflow
  # put a test case into the subfolder .test (e.g., use https://github.com/snakemake-workflows/ngs-test-data as a submodule)
  - python -m test_fumic
